version: '3'

services:
  pyjamas:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
      - phpmyadmin
    environment:
      DB_HOST: db:3306
      DB_USER: user
      DB_PASSWORD: user_pw

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: pyjamas
      MYSQL_ROOT_PASSWORD: XTmDQ3TbQf$z3dm
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: pyjamas
      MYSQL_PASSWORD: PYJAMAS_FHNW
    volumes:
      - db:/var/lib/mysql
    ports: # only for using from outside / not necessary for pyjamas
      - "3306:3306" # delete for security reason

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8181:80 # use "localhost:8181" for phpMyAdmin
    environment:
      MYSQL_USERNAME: pyjamas
      MYSQL_PASSWORD: PYJAMAS_FHNW
      MYSQL_ROOT_PASSWORD: XTmDQ3TbQf$z3dm

# mount volume for persistent data in DB
volumes:
  db:
  # to list all volumes:  docker volume ls
  # to delete volume:     docker volume rm pyjamas_db