version: '3'

services:
  pyjamas:
    build: .
    volumes:
      - .:/app
    ports:
      - 80:5000
    links:
      - db
    depends_on:
      - db
      - phpmyadmin
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      FLASK_DEBUG: 1

      FLASK_USER_EMAIL: pyjamas@fhnw.ch
      FLASK_USER_PASSWORD: PYJAMAS_FHNW

      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pyjamas
      DB_USER: pyjamas
      DB_PASSWORD: PYJAMAS_FHNW

      SECRET_KEY: pyjamas_secret
      SECURITY_PASSWORD_SALT: /7fD8Ff84gX6Q5r46k452fcvyxedw
      SECURITY_REGISTERABLE: 0
      SECURITY_PASSWORD_HASH: bcrypt
      SQLALCHEMY_TRACK_MODIFICATIONS: 0

  db:
    #RPi: image: jsurf/rpi-mariadb:latest
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pyjamas
      MYSQL_ROOT_PASSWORD: XTmDQ3TbQf$z3dm
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: pyjamas
      MYSQL_PASSWORD: PYJAMAS_FHNW
    volumes:
      - db:/var/lib/mysql
    ports: # only for using from outside / not necessary for pyjamas
      - "3306:3306" # delete for security reason

  phpmyadmin:
    #RPi: image: sk278/phpmyadmin-armhf (not working)
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 81:80 # use "localhost:81" for phpMyAdmin
    environment:
      MYSQL_USERNAME: pyjamas
      MYSQL_PASSWORD: PYJAMAS_FHNW
      MYSQL_ROOT_PASSWORD: XTmDQ3TbQf$z3dm

# mount volume for persistent data in DB
volumes:
  db:
  # to list all volumes:  docker volume ls
  # to delete volume:     docker volume rm pyjamas_db